### ISSUE TITLE
Critical and high vulnerabilities found in deployment images

### ISSUE THREAD

**Issue by fallard84** [Portshift/kubei#22]
I saw the `kubeiShouldScan` flag on some of the deployment resources so I decided to scan all images used to deploy kubei, using Google Container Registry scanner. A lot of critical, high and medium vulnerabilities were found:

- postgres:9.6.5: 5 critical, 22 high, 58 medium
- clair-db: 3 high
- clair-local-scan: 9 high

Kubei looks interesting as a solution but isn't it a bit ironic that a vulnerability scanner solution uses vulnerable images as part of its deployment? 🤷‍♂️ 😅

**Comment by akpsgit** [comment]
Hi @fallard84, thanks a lot for letting us know. We'll update the images and remove the kubeiShouldScan flag to avoid it in the future.

**Comment by FrimIdan** [comment]
Hi @fallard84 I'm closing this issue since all images were updated and currently there are no vulnerabilities.
Thanks again, please re-open if you have any further questions.
