### ISSUE TITLE
ADD service account option to spawned scanning containers 

### ISSUE THREAD

**Issue by HackyPenguin** [Portshift/kubei#35]
Hi Guys I started playing with kubei today however it seems to lack an option to configure the service  account to use for the spawned scanning containers. This causes loads of issues when working inside a security-conscious k8s container with restrictive PSP's.  Namely, the scans won't start as they load under the default PSP policy, not the policy assigned to the service account. 

Fix: allow an argument to be passed along the lines of SCANNER_SERVICE_ACCOUNT which will point to a k8s service account to be used by the scanning agent.

**Comment by akpsgit** [comment]
Hi @HackyPenguin, thanks a lot for the feedback and the suggestion. We can add this but the scanning pods are created in the same namespace as the pod they scan to use the pull credentials. This means that the given service account should be present in all the scanned namespaces. WDYT?

**Comment by HackyPenguin** [comment]
yea a SA per namespace makes sense. Probably best to have a whitelist of namespaces when using this feature then create that SA in each ns linking to a central cluster role binding.  We can then package the kube.yaml into helm and have it generate these Service accounts based on the params passed when Kubei is installed.
