### ISSUE TITLE
Failing to deploy.

### ISSUE THREAD

**Issue by videoman** [Portshift/kubei#37]
When I attempt to apply this image, it never starts- and there is an error within the postgres pod.

This is the output from the "kubectl -n kubei get events" command:
```
10s         Warning   InspectFailed       pod/clair-postgres-6775b5bdc6-j2pml    Failed to inspect image "gcr.io/portshift-release/clair/clair-db": rpc error: code = Unknown desc = Error response from daemon: readlink /var/lib/docker/overlay2/l: invalid argument
10s         Warning   Failed              pod/clair-postgres-6775b5bdc6-j2pml    Error: ImageInspectError
```

I would guess that something in that image or app failed.

**Comment by FrimIdan** [comment]
Hi @videoman,

Can you please share more info on your environment, I've tried it on GKE and it works
```
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.401", GitCommit:"eb94c181eea5290e9da1238db02cfef263542f5f", GitTreeState:"clean", BuildDate:"2020-09-09T00:57:35Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

Maybe the following issues are related:
https://github.com/docker/for-mac/issues/1396
https://github.com/kubernetes/kubeadm/issues/738

**Comment by videoman** [comment]
It's docker on CentOS.
