### ISSUE TITLE
kube-bench vs kubei

### ISSUE THREAD

**Issue by estahn** [Portshift/kubei#45]
Would you mind explaining what the difference between kubei and [kube-bench](https://github.com/aquasecurity/kube-bench) is? Does this cover the same area?

**Comment by ArielShup** [comment]
Kube-bench tests security best practices following the CIS Benchmark tests. It runs on each of your nodes checking if the configurations meet best practice recommendations from the CIS community.
Kubie focus is on vulnerabilities detection in your code, it checks for known vulnerabilities in your pods code by pulling the images used in specific cluster (or namespace) scanning their packages, dependencies for known vulnerabilities. 
It complements the Kube-bench configurations tests.
