### ISSUE TITLE
Is it possible to scan ECR using kube2iam?

### ISSUE THREAD

**Issue by giovannirco** [Portshift/kubei#48]
I liked the project and will try it out tomorrow but I am wondering if anyone got it working with kube2iam. I cannot create users and get access key and secret to setup on k8s. I am coming from starboard as it seemed to be a good option but it relies on IRSA which I don't have it configured right now and couldn't make it work with kube2iam

**Comment by FrimIdan** [comment]
ECR support info is listed here (https://github.com/Portshift/kubei#amazon-ecr-support)
I'm not sure I understand how kube2iam is related here.
