### ISSUE TITLE
SecurityContextes & dropping privileges

### ISSUE THREAD

**Issue by faust64** [Portshift/kubei#56]
As initially reported there: https://github.com/Portshift/Kubei/issues/20
And partially fixed here: https://github.com/Portshift/kubei/pull/25/files

Note that every container created by Kubei is also subject to broken securityContexts, leading to Jobs being created while their Pods are stuck:

```
  Normal   Scheduled  4m42s                  default-scheduler  Successfully assigned registry/scanner-docker-registry-exporter-1042b89a-080d-4dad-b84d-1lwpq8 to compute2
  Normal   Pulling    4m42s                  kubelet            Pulling image "gcr.io/eticloud/k8sec/klar:1.0.16"
  Normal   Pulled     4m16s                  kubelet            Successfully pulled image "gcr.io/eticloud/k8sec/klar:1.0.16" in 26.151366977s
  Normal   Pulling    4m16s                  kubelet            Pulling image "gcr.io/eticloud/k8sec/dockle:1.0.3"
  Normal   Pulled     3m54s                  kubelet            Successfully pulled image "gcr.io/eticloud/k8sec/dockle:1.0.3" in 21.426950017s
  Warning  Failed     3m10s (x5 over 3m54s)  kubelet            Error: container has runAsNonRoot and image will run as root
  Warning  Failed     2m56s (x6 over 4m16s)  kubelet            Error: container has runAsNonRoot and image will run as root
```

Vulnerability scanners that can't run on secured clusters may miss its target audience.

https://github.com/Portshift/kubei/blob/master/pkg/scanner/job-manager.go#L386 may need some fix, inserting proper SecurityContext while generating jobs pod template. Sadly, I'm no Go expert, ...
Anyone here that would both understand the issue and how to best fix it?

**Comment by faust64** [comment]
Out of curiosity, I'm trying to figure how to code in Go ... and as I was suspecting, it's quite a pain. After about 2 hours,  I finally have something that compiles:

```
diff --git a/pkg/scanner/job-manager.go b/pkg/scanner/job-manager.go
index aff55a6..cd10c86 100644
--- a/pkg/scanner/job-manager.go
+++ b/pkg/scanner/job-manager.go
@@ -257,6 +257,8 @@ func (s *Scanner) createVulnerabilitiesScannerContainer(imageName, secretName st
 
        env = s.appendProxyEnvConfig(env)
 
+       i := func(i int64) *int64 { return &i }
+
        if secretName != "" {
                log.WithFields(s.logFields).Debugf("Adding private registry credentials to image: %s", imageName)
                env = append(env, corev1.EnvVar{
@@ -288,6 +290,9 @@ func (s *Scanner) createVulnerabilitiesScannerContainer(imageName, secretName st
                                corev1.ResourceMemory: resource.MustParse("10Mi"),
                        },
                },
+               SecurityContext: &corev1.SecurityContext{
+                       RunAsUser: i(1000),
+               },
        }
 }
```

Though I would assume adding this should be optional. And I still haven't tested it.
I'm done with curiosity for tonight ...

**Comment by akpsgit** [comment]
Hi @faust64, thanks a lot for pointing this. Instead of hardcoding the security context information, we can read it from a config map during Kubei's init and start the job accordingly. Then, we can either watch the configuration for changes or require to restart the pod to read it. WDYT?

**Comment by faust64** [comment]
Sure. ConfigMap, env vars. Either one would be nice.

**Comment by FrimIdan** [comment]
@faust64 did you configured a PSP to enforce `runAsNonRoot`? If so, configuring the policy to also enforce `runAsUser` will not solve the issue?

**Comment by faust64** [comment]
I'm using the PSP shipping with Kubespray.
The default, `restricted`, says:

```
spec:
  allowPrivilegeEscalation: false
  forbiddenSysctls:
  - '*'
  fsGroup:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  requiredDropCapabilities:
  - ALL
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  volumes:
  - configMap
  - emptyDir
  - projected
  - secret
  - downwardAPI
  - persistentVolumeClaim
```

I don't really want to force add a runAsUser: I know I have containers that would expect to run as UID 1000, others as 1001, others as 4242, I've seen 1337, 65534. Some images I build myself (uid 1000), others picked here and there...
I wouldn't want to prevent those from writing files and folders they currently have access to
I'ld rather not wait for those to crash, to figure out which is which, and where should I force securityContexts or mount emptyDirs next
Also, changing owners UID on larger PVCs, with lots of inodes, could be painful.

I wouldn't want Kubespray upgrades wiping my PSP customization either - thus, I avoid changing defaults. If I need something, I grumble while creating a new PSP, an SA, Role, RoleBinding.
Though I don't see a reason to make an exception here.

Indeed, the real issue isn't necessarily Kubernetes configuration related.
The source of those errors is basically the Kubei Dockerfile, not setting a USER, thus running as root.
Best practices would usually advise to set a numeric user ID:

 - https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user
 - https://sysdig.com/blog/dockerfile-best-practices/ (chapter 1.1)

Besides, having forced Kubei container UID myself, I doesn't look like running as root is a requirement.
Is there any reason Kubei would need to run as root, that I may have missed?
A simpler patch may just be to add a `USER 12345` in the end of that Dockerfile.

**Comment by FrimIdan** [comment]
I agree with you, Kubei and the scanners (Klar and Dockle) doesn't need to run as root - we probably need to update the docker files.

**Comment by faust64** [comment]
Right, ... and thinking back out it: the securityContext I've added here applies to the klar container, actually.
Fixing the klar Dockerfile would avoid  the issue I've mentioned here.
While fixing the Kubei Dockerfile should spare us from: https://github.com/Portshift/kubei/pull/25

**Comment by Jaybe-bdk** [comment]
Could somebody look at the PR? I want to use kubei but our PSP did not allow the usage of root user in images.

**Comment by faust64** [comment]
The PR #25 would only fix issues related to starting the Kubei container itself. Though that container also starts Klar Pods, when scanning images, also running as root.

If you have some place to push custom images, you would have to build your own Kubei, patching pkg/scanner/job-manager.go -- one sample to do it would be https://github.com/Portshift/kubei/issues/56#issuecomment-873258899, assuming your PSP allows containers starting with UID `1000`.

We should probably introduce some variable / argument, allowing to set this or not, and changing the UID when necessary. Until then, a PR at that stage may not fit all use cases.
I should have looked into this ... If you're up for it, feel free to submit your own PR.

**Comment by FrimIdan** [comment]
Hi All, sorry for the delay.
https://github.com/Portshift/kubei/pull/60 should fix the user issue for Kubei and the scanners.
Please let me know if something is missing, closing the issue for now.
