### ISSUE TITLE
Recommended resources for a kubei container

### ISSUE THREAD

**Issue by chencivalue** [Portshift/kubei#6]
Hello Team and thanks for sharing this project with the open source community !
I'd like to deploy kubei on my cluster and couldn't see any resources limitations in the deployment object.  What are the minimum RAM and CPU a kubie container needs in order to operate well?
Thanks!

**Comment by akpsgit** [comment]
Hey @chencivalue, thanks a lot for pointing out the issue. We added the required resources and limits as we measured it across several deployments. Thanks!!

**Comment by chencivalue** [comment]
Appreciate it, thanks!
