### ISSUE TITLE
i want to scan pods just in local host.

### ISSUE THREAD

**Issue by Z000000** [Portshift/kubei#67]
if i want to scan pods just in local host, i donot want the kubei to pull the images throught the http or https protocol ,is there a param to set and make function?

I hava some images which do not exist in the harb repository,it comes from third repository,but my Internet cannot connect to it,so i want the kubei just scan in the localhost.

**Comment by akpsgit** [comment]
Hi,
The current implementation Kubei uses Grype (as a server) to scan the images. You can run the klar (https://github.com/Portshift/klar) binary (Grype client) locally and to set the destination address of the Grype server. But I think that it's over complication, and better to just use Grype locally. We are working on Kubei2, which will also have a full cli support (should be ready in a couple of weeks).

**Comment by Z000000** [comment]
> Hi, The current implementation Kubei uses Grype (as a server) to scan the images. You can run the klar (https://github.com/Portshift/klar) binary (Grype client) locally and to set the destination address of the Grype server. But I think that it's over complication, and better to just use Grype locally. We are working on Kubei2, which will also have a full cli support (should be ready in a couple of weeks).

ok thank you very much
